# Generated by Django 5.1.7 on 2025-04-04 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=200)),
                ('schedule', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('therapy_type', models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical')], max_length=50)),
                ('schedule', models.CharField(max_length=200)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy_booking.therapist')),
            ],
        ),
    ]
